service: food-net-scrapers

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  timeout: 900
  environment:
    IN_LAMBDA: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:DescribeTable
      Resource:
        - "*"

layers:
  chromedriver:
    path: headless-chromium
    description: "chrome driver layer"
    CompatibleRuntimes: [
      "python3.6"
    ]

package:
  include:
    - '../server/entities/resteraunt.py'
    - 'suburbs.py'

functions:
  scrape_zomato:
    handler: zomato_scraper.scrape_zomato
    events:
      - schedule:
          rate: rate(12 hours)
    layers:
      - {Ref: ChromedriverLambdaLayer}
  scrape_google:
    handler: google_review_scraper.scrape_google
    events:
      - schedule:
          rate: rate(12 hours)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: /usr/bin/python3